### ISSUE TITLE
HTTP Verbs should be lower case

### ISSUE THREAD

**Issue by coryasilva** [coldbox-modules/cbSwagger#1]
When validation the OpenAPI schema, I get an error about `POST` not being allowed.  Looking at the documentation it should be `post`.  

**Validator**
http://editor.swagger.io/#/

**Test Case:**
```
{
  "swagger": "2.0",
  "info": {
    "version": "",
    "title": ""
  },
  "host": "app.domain.com",
  "basePath": "/api",
  "paths": {
    "/api/endpoint": {
      "POST": {
        "responses": {
          "default": {
            "description": ""
          }
        },
        "x-resourceId": ""
      },
      "x-resourceId": ""
    }
  }
}
```

**Comment by coryasilva** [comment]
Changing `ucase` to `lcase` in the following lines of the RoutesParser should suffice.

- https://github.com/coldbox-modules/cbSwagger/blob/development/modules/cbswagger/models/RoutesParser.cfc#L193
- https://github.com/coldbox-modules/cbSwagger/blob/development/modules/cbswagger/models/RoutesParser.cfc#L196
- https://github.com/coldbox-modules/cbSwagger/blob/development/modules/cbswagger/models/RoutesParser.cfc#L203
- https://github.com/coldbox-modules/cbSwagger/blob/development/modules/cbswagger/models/RoutesParser.cfc#L205

**Comment by lmajano** [comment]
Thanks, fixed now

**Comment by coryasilva** [comment]
Thank you!
