### ISSUE TITLE
Specify a security scheme for an endpoint

### ISSUE THREAD

**Issue by neffnet** [coldbox-modules/cbSwagger#14]
Our API authenticates users with a "UserSecurity" web token or with a shared key "AuthenticationToken." We defined these in the cbswagger config, now they both appear at the top of our Redoc page and are referenced in every endpoint description. Most functions authenticate with either method, but a few require AuthenticationToken specifically. How can we specify that one endpoint requires a specific security type?

**Comment by jclausen** [comment]
Could you paste in an example of your configuration?  If you define a `securitySchemes` config, but don't define a `security` node in the config ( https://github.com/coldbox-modules/cbSwagger#configure-cbswagger-to-auto-detect-your-api-routes ), you can then specify it only in the handler docblock for those routes to which it applies:

```
@security /resources/apidocs/security/security-enforced.json
```
The document `security-enforced.json` might have a schema like:

```
[
		{ "APIKey" : [ "Read", "Write", "Delete" ] },
		{ "BasicAuthentication" : [ "Read", "Write", "Delete" ] }
]
```

**Comment by neffnet** [comment]
Thanks Jon. I think cbswagger is not picking up the `@security` annotation.

Taken from `components` part of our cbswagger config:
```
"securitySchemes" : {
	"UserSecurity" : {
		"type" 			: "http",
		"description" 	: "JWT Basic auth",
		"scheme" 		: "bearer",
		"bearerFormat"  : "JWT"
	},
	"AuthenticationToken" : {
		"description": "...",
		"type"       : "sharedKey",
		"name"       : "AuthenticationToken",
		"in"         : "header",
		"example"    : ""
	}
}```

Currently there are no security nodes defined, and the references to UserSecurity and AuthenticationToken no longer appear on each function in our docs, only at the top. I edit the handler to update a function's annotations, putting `* @security /resources/api/security.AuthenticationToken.json`, and the contents of that file:
```
[
  { "AuthenticationToken": [ "Read","Write","Delete" ] }
]
```
There is no change to the output spec.

I can see where some of the annotations get handled in RoutesParser.cfc, but I don't see anything handling @security

**Comment by jclausen** [comment]
Try it as x-security.  I’ll take a look at the code to see why it’s not pulling it in as a first class annotation

**Comment by neffnet** [comment]
Still nothing if I change it to @x-security. If I use x-security as a function attribute `function doThing() x-security="path.json"`, I can see my AuthenticationToken has been added to that endpoint in the spec json from cbswagger, but it isn't picked up in the generated redoc page.

**Comment by lmajano** [comment]
Remember that the open api 3.x spec changed the way security schemas are defined

Luis F. Majano
CEO

E: lmajano@ortussolutions.com (https://link.getmailspring.com/link/72A306A0-3DA6-41A8-9517-2CDDB63A0F3C@getmailspring.com/0?redirect=mailto%3Almajano%40ortussolutions.com&recipient=cmVwbHkrQUFCQlBGNlhVVVRTV0daV0xYWUpSQTUzN1pVUEJFVkJOSEhCNzQ1MkFVQHJlcGx5LmdpdGh1Yi5jb20%3D)
P: 909-248-3408 (tel:909-248-3408)1-888-557-8057 (tel:1-888-557-8057) (Fax)
A: Houston, Texas (https://link.getmailspring.com/link/72A306A0-3DA6-41A8-9517-2CDDB63A0F3C@getmailspring.com/1?redirect=https%3A%2F%2Fmaps.google.com%2F%3Fq%3DHouston%252C%2520Texas&recipient=cmVwbHkrQUFCQlBGNlhVVVRTV0daV0xYWUpSQTUzN1pVUEJFVkJOSEhCNzQ1MkFVQHJlcGx5LmdpdGh1Yi5jb20%3D)
W: http://www.ortussolutions.com (https://link.getmailspring.com/link/72A306A0-3DA6-41A8-9517-2CDDB63A0F3C@getmailspring.com/2?redirect=http%3A%2F%2Fwww.ortussolutions.com&recipient=cmVwbHkrQUFCQlBGNlhVVVRTV0daV0xYWUpSQTUzN1pVUEJFVkJOSEhCNzQ1MkFVQHJlcGx5LmdpdGh1Yi5jb20%3D)

**Comment by neffnet** [comment]
https://github.com/coldbox-modules/cbSwagger/pull/18
