### ISSUE TITLE
Remove entry route from generated docs

### ISSUE THREAD

**Issue by neffnet** [coldbox-modules/cbSwagger#15]
We're using cbSwagger to generate an API spec and we pass it to Redoc to auto-generate a public API docs page. This is working very nicely, except that we end up with several `<no summary>` routes at the top of the document, each pointing to the API base URL `/api/v1/`. Is this intended behavior or perhaps something is wrong with our API configuration? We want to remove these "empty" routes from our documentation.

Thank you!

**Comment by jclausen** [comment]
@neffnet : This has to do with a default route declared in one of your routing files ( `ModuleConfig.cfc`, `Router.cfc`, etc. )   

Something like `route( "/", "Handler.method" );` ( in Coldbox 5 routing syntax )

Remove the default route and this empty one will go away.

**Comment by neffnet** [comment]
Thanks, Jon.
Well I wasn't able to find where that default route is coming from, so I made a way for cbswagger to exclude it instead: https://github.com/coldbox-modules/cbSwagger/pull/16
