### ISSUE TITLE
Path's Parameters not always an array

### ISSUE THREAD

**Issue by coryasilva** [coldbox-modules/cbSwagger#2]
**Problem**
When referencing a nested property on a JSON file, instead of returning the nested property's value we get the path string.  
`ie:  x-parameters /includes/resources/users.add.parameters.json##user`

**Reasoning**
The swagger spec does not allow for a string for `parameters` _(unless I am reading it incorrectly which is very possible)._

**Steps to reproduce**
Add a line to `writeDump( NormalizedDoc );` in [this testcase](https://github.com/coldbox-modules/cbSwagger/blob/development/tests/specs/unit/RoutesParserTest.cfc#L33) and see that the `NormalizedDoc["paths"]["/api/v1/users"]["post"]["parameters"]` is a string instead of an array.

**Comment by vitamindck** [comment]
Hopefully this helps you.. I spent a lot of time trying to figure out from the docs what is going on with this module.
```
/**
* @description brief description of the endpoint
* @x-parameters /filepath/to/parameters/json
*/
function nameOfFunction( event, rc, prc ) {
    // code
}
```

cbSwagger seems to follow the [Parameters Definition Object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#parametersDefinitionsObject) model. My parameters are structures instead of arrays. It would be nice to be able to use arrays so I don't have to create additional keys inside my parameters object.

cbSwagger expects this
```
{
	"someparam": {
		"name": "someparam",
		"description": "this is some parameter",
		"required": true,
		"type": "string"
	},
	"otherparam": {
		"name": "otherparam",
		"description": "this parameter was adopted",
		"required": true,
		"type": "string"
	}
}
```

but this could work, too, if I'm reading the API docs correctly...

```
[{
	"name": "someparam",
	"description": "this is some parameter",
	"required": true,
	"type": "string"
}, {
	"name": "otherparam",
	"description": "this parameter was adopted",
	"required": true,
	"type": "string"
}]
```

**Comment by coryasilva** [comment]
@vitamindck Thank you for also looking into this!   Just wanted to note a couple of observations:

- As I understand, the "Parameters Definition Object" is not meant to be nested under the "paths" but instead a top level key.  
- http://editor.swagger.io/ still reports that the path.['/endpoint'].parameters needs to be an array and does not render the parameters. 
- The third code snippet above is invalid JSON and will throw a parser error.

**Comment by jclausen** [comment]
@coryasilva and @vitamindck :  Thanks for the feedback!  Path item parameters are always an array of objects, but can reference the definition object.  See the path example:  https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#path-item-object

So, to reference the path definition object, within the individual parameters, you could do the following:

```
"parameters" : [
    {"$ref" : "#parameters.myParam}
]
```

Or you could use the `$ref` at the top level to point to an external file with the array of parameters:

```
"parameters" : { "$ref" : /includes/resources/users.add.parameters.json#user }
```

Either are valid.

I do see what you're saying with regard to the string parsing. It appears that external references are not always being picked up correctly with the `x-parameters` attribute and, as such, it's not being cast properly when the swagger doc is generated.  

I'll look in to an improvement to the parsing of that particlular item and  get a fix for that pushed up shortly.

**Comment by lmajano** [comment]
It should be up to open api 3.x spec now.
