### ISSUE TITLE
`x-resourceId` should only show up in the method operations not everywhere

### ISSUE THREAD

**Issue by lmajano** [coldbox-modules/cbSwagger#20]
`x-resourceId` should only show up in the method operations not everywhere

**Comment by jclausen** [comment]
The next iteration should remove that from the `cbSwagger` output, completely, and we can put it in to the post-processing of Relax.    We'll need to pin the `cbswagger` version on the current relax version, though.

**Comment by jclausen** [comment]
The handling of `x-resourceId` keys has been removed in cbSwagger v3 ( currently in snapshot )
