### ISSUE TITLE
/cbswagger/yml output is not valid YML

### ISSUE THREAD

**Issue by MordantWastrel** [coldbox-modules/cbSwagger#23]
* No indentation
* Line breaks in text

Both are evident in just the first few lines of our cbSwagger output:

```
openapi: 3.0.2
info:
termsOfService: ''
title: inLeague API
version: v1
contact: {url: 'https://www.inleague.io', name: inLeague Support, email: support@inleague.io}
license: {url: '', name: Use of this API is restricted to entities authorized by
an operating agreement with inLeague LLC.}
servers:
```

**Comment by jclausen** [comment]
@MordantWastrel : Could this be something in the way your browser is rendering the file?  When I hit the yaml endpoint, my browser doesn't know what to do with it and it downloads the file.  When I open that file, it's the expected two-space indented YAML representation.

**Comment by MordantWastrel** [comment]
It downloads it on my end as well - no browser rendering. The example above is pasted from a text editor opening that download.

**Comment by jclausen** [comment]
OK. Are you on Windows?  Also, could you give me browser information?  

Lastly, do you see any difference in the file contents if you change the `renderData` `contentType` argument on line 62 of `modules/cbSwagger/handlers/Main.cfc` to the mimetype `application/x-yaml` or `text/yaml` ?

**Comment by MordantWastrel** [comment]
CF is running in Docker (WSL2) but the host doing the downloading and opening is Windows 10 19041.

Tried Chrome 81, Edge, and Firefox 75.

No change on the content types.

**Comment by illequipped** [comment]
bumping. YML output is missing formatting and does not validate.

**Comment by jclausen** [comment]
As far as I can tell, this issue appears to be resolved in v3 of `swagger-sdk` and `cbswagger` which are both in snapshot state.

I have downloaded the YML document ( generated by the java SnakeYAML library from the JSON representation of the API ) and have been able to paste it in to Redoc whithout any issues.  I've also tried it with several YML parsers.

Please re-open if this is still an issue after the next release.
