### ISSUE TITLE
x-resourceId in responses breaks swagger.io output

### ISSUE THREAD

**Issue by illequipped** [coldbox-modules/cbSwagger#27]
If you use swagger.io, the existence of x-resourceId in 'responses' causes it to display "😱 Could not render n, see the console."

`{
  "responses": {
    "200": {
      "description": "Success"
    },
    "400": {
      "description": "Not Found"
    },
    "default": {
      "description": ""
    },
    "x-resourceId": "a9f0a3a63fe6b5bd954760c6ac09e85c"
  }
}`

Looks like #20 would resolve this

**Comment by ThomasMcDonald** [comment]
@jclausen Any update on this issue? Still occurs with the current version available on forgebox

**Comment by jclausen** [comment]
@ThomasMcDonald Let me look.  It looks like the 2.7 release never published to Forgebox.  I am re-running the build to get that version published.

**Comment by jclausen** [comment]
I am going to be making this change in the Swagger SDK and we will make these resource identifiers a UI concern, going forward.

**Comment by jclausen** [comment]
The handling of `x-resourceId` keys has been removed in cbSwagger v3 ( currently in snapshot )
