### ISSUE TITLE
request : make 'default' optional in Responses

### ISSUE THREAD

**Issue by illequipped** [coldbox-modules/cbSwagger#28]
We use swagger.io to publish our api. There is no way to disable 'default' from outputting to Responses. We define all of our response codes.

**Comment by lmajano** [comment]
Can you paste some examples for us to analyze. I can't visualize what you are defnining please!
Thanks

**Comment by illequipped** [comment]
Thanks @lmajano.  Its actually set in swagger-sdk. Line 70 of Util.cfc. Default is always appended to the response object. Its not really necessary if you define all responses from your api. 

![Screen Shot 2021-03-04 at 11 00 39 AM](https://user-images.githubusercontent.com/36807144/109992076-e9124180-7cd8-11eb-8a9b-5d8731e48f33.png)

And you can see the error that #27 causes right below it.

**Comment by homestar9** [comment]
I'd like to piggyback on this issue and add my opinion that `default` shouldn't be inserted into the schema automatically - especially when it comes to required params.

RoutesParser.cfc automatically adds an empty string to `schema.default` here:
https://github.com/coldbox-modules/cbSwagger/blob/191706b95d1787cd743c9efffdcd27360f60f3ba/models/RoutesParser.cfc#L412-L424

And when writing out function params here:
https://github.com/coldbox-modules/cbSwagger/blob/191706b95d1787cd743c9efffdcd27360f60f3ba/models/RoutesParser.cfc#L757-L764

I feel like it would be more intuitive to not populate `schema.default` for all params unless the user specifically states it in the metadata like this `{ "name": "firstName", "type": "string", "required" : "false", "in" : "query", default: "" }` 

For new users of cbswagger, it will help keep their final config cleaner and it gives advanced users more control.

**Comment by jclausen** [comment]
This duplicates https://github.com/coldbox-modules/swagger-sdk/issues/14  This change is targeted for the next release.

**Comment by jclausen** [comment]
This is resolved by commit #2aea679 and will be part of the v3.0.0 release.  If other status code keys are present and the `default` key is empty, it will be removed.
