### ISSUE TITLE
Unpacking components fails to generate valid swagger documentation.

### ISSUE THREAD

**Issue by ThomasMcDonald** [coldbox-modules/cbSwagger#32]
Version: [2.6.0+147](https://www.forgebox.io/view/cbSwagger) 

Components should not be unpacked within the schema, instead they should be referenced as current OpenAPI documents do.

Found a temporary work around by adding this line to Parser.cfc line 191 within the fetchDocumentReference function.
```
if (findNoCase("##/components", $ref)) {
  return { "$ref": $ref }
}
```

Coldbox.cfc cbswagger config

```
"components" : {
	// Define your security schemes here
	// https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#securitySchemeObject
	"securitySchemes" : {},
	"schemas": {
		"Response": {
			"$ref": '/resources/apidocs/Base/Response.json'
		},
		"User": {
			"$ref": '/resources/apidocs/_schemas/personnel/personnel.json'
		}
	}
}
```

Response JSON
```
{
    "200": {
        "description" : "User Response",
        "content" : {
            "application/json" : {
                "schema": {
                    "allOf": [
                        {
                            "$ref":  "#/components/schemas/Response"
                        },
                        {
                            "type": "object",
                            "properties": {
                                "data": {
                                    "$ref":  "#/components/schemas/User"
                                }
                            }
                        }
                    ]
                }
            }
        }
    }
}
```

**Comment by lmajano** [comment]
I am confused. Can you point out the docs on the schema please. Thanks

**Comment by ThomasMcDonald** [comment]
@lmajano Sorry I probably could have been more descriptive. [Docs for swagger components](https://swagger.io/docs/specification/components/)

I have set up a [test repo](https://github.com/ThomasMcDonald/cbswagger-test) using the very basic REST skeleton from the [tutorial](https://coldbox.ortusbooks.com/digging-deeper/recipes/building-rest-apis). I have made the necessary tweaks to replicate my issue in the original post.

When accessing the /cbswagger endpoint I get this. The issue persists when using the adobe engine and Lucee engine.
![image](https://user-images.githubusercontent.com/11895741/182249564-6c6987ab-07cd-4096-b9e9-57ae4b2ac51d.png)

From my testing it looks like the main issue are the references to the components. If I remove them from the responses.json the swagger generates fine OR if I add my code snippet from above.

Worth noting that the components themselves generate fine at the bottom of the document.
[Expected Result](https://github.com/ThomasMcDonald/cbswagger-test/blob/main/expectedResult.yml).

Off topic for this issue but it appears that #27 is still an issue.

**Comment by jclausen** [comment]
This is resolved in v3 of `swagger-sdk`, which is currently in pre-release snapshot.
