### ISSUE TITLE
Feature: Ability to add Additional Schema Components Via Metadata

### ISSUE THREAD

**Issue by homestar9** [coldbox-modules/cbSwagger#34]
Swagger has some functionality for defining complex data models using inheritance and polymorphism ((https://swagger.io/docs/specification/data-models/inheritance-and-polymorphism/).  However, there doesn't seem to be an easy way to include additional component definitions with cbswagger.

Adding this ability would be a huge time-saver for API developers because they could extend the default response object for each API resource. 

```
// component definition for the product specific response object
"components": {
    "schemas": {
        "Response": {
            "allOf": [
                {
                    "$ref": "../../_schemas/app-response.json"
                },
                {
                    "type": "object",
                    "properties": {
                        "data": {
                            "description": "A single Product",
                            "$ref": "../../_schemas/product.json"
                        }
                    }
                }
            ]
        }
    }
}
```

Perhaps the best way to do this would be to allow for an additional metadata annotation called `@components` which would work like this:

```
/**
 * Show a Product
 * 
 * @x-route (GET) /api/v1/products/:id
 * @tags Products
 * @description Returns the details of a specific Product by Id
 * @x-parameters /api-v1/_apidocs/products/show/parameters.json##parameters
 * @response-default /api-v1/_apidocs/products/show/responses.json##200
 * @components /api-v1/_apidocs/products/show/components.json##components <!-- New metadata
 */
function show( event, rc, prc ) {
    // ... code
}
```

Then a response.json file could reference the new component like this:
```
{
    "200": {
        "description": "200-Success",
        "content": {
            "application/json": {
                "schema": {
                    "$ref": "#/components/schemas/Response" <!-- References the schema
		}
            }
        }
}
```

**Comment by jclausen** [comment]
I will look at adding this to the next release, once `allOf` functionality is passing in `swagger-sdk`

**Comment by homestar9** [comment]
The way I'm currently working around this is by adding a new key in my cbswagger model config, which references a JSON file that adds all of the schemas I need. The config looks like this:

```
// config/Coldbox.cfc module settings
cbswagger = {
	"routes" : [],
	"excludeRoutesPrefix" : [ "cbswagger" ],
	"excludeRoutes"	: [],
	"defaultFormat" : "json",
	"samplesPath" : "resources/apidocs",
	// Information about your API
	"info"		:{...},
	"tags" : [...],
	"servers" : [...],
	"components" : {
		"securitySchemes" : {...},
		"schemas": {
			"$ref": "/resources/apidocs/_schemas/all.json" <-- JSON file containing all schemas
		}
	}
}
```

Then, the all.json file looks like this:
```
{
    "Response": { "$ref":"response.json" },
    "Pagination": { "$ref":"pagination.json" },
    "Product": { "$ref": "product.json" },
    
    "Media": { "$ref": "../media/_schemas/media.json" },
    "MediaBook": { "$ref": "../media/_schemas/mediaBook.json" },
    "MediaMusic": { "$ref": "../media/_schemas/mediaMusic.json" }
}
```

It's not really OO because the all.json file needs to know every single schema, but maybe that's okay for documentation purposes.  Either way, it gets the job done.

@jclausen, maybe this workaround using the config is a better approach? I would be curious to hear what you think would best from a documentation/workflow perspective.

**Comment by jclausen** [comment]
After looking at this a bit more, I really feel like it's the responsibility of the top level document or the child document to have pointers that are resolvable with itself.  

It feels messy (and potentially buggy) to me to supply components in the annotation, which are then referenced in the files being brought in.

To me, this feels like a better way of defining:

```
{
    "responses" : {
        "200": {
            "description": "200-Success",
            "content": {
                "application/json": {
                    "schema": {
                        "$ref": "#/components/schemas/Response"
                    }
                }
            }
        }
    },
    "components" : {
        "schemas": {
            "Response": {
                "allOf": [
                    {
                        "$ref": "../../_schemas/app-response.json"
                    },
                    {
                        "type": "object",
                        "properties": {
                            "data": {
                                "description": "A single Product",
                                "$ref": "../../_schemas/product.json"
                            }
                        }
                    }
                ]
            }
        }
    }
    
}
```
where handler annotations would be:

```
/**
 * Show a Product
 * 
 * @x-route (GET) /api/v1/products/:id
 * @tags Products
 * @description Returns the details of a specific Product by Id
 * @x-parameters /api-v1/_apidocs/products/show/parameters.json##parameters
 * @response-default /api-v1/_apidocs/products/show/responses.json##responses.200
 */
function show( event, rc, prc ) {
    // ... code
}
```

Now that we have added inheritance support, the document can then resolve to itself when it is sourced in.

**Comment by jclausen** [comment]
I'll leave this open for a bit, as I'm open to influence, but I'm leaning toward not addressing this right now. It feels like too much like it breaks encapsulation with the OpenAPI objects, themselves

**Comment by homestar9** [comment]
I believe part of the issue is the Parser tries to inject `$ref` **values** that start with "#" instead of treating them as document **references** and leaving them as-is.   Currently there is no way to reference the swagger document itself using "#" because of the Parser's current behavior.  Perhaps we should use a different character other than "#" if you want to inject the value of an internal document key? Perhaps a "##", "%", or "$"?

Here's an example of how PetStore defines and references schemas. I circled the references and placed dots next to the schema definitions:
![image](https://user-images.githubusercontent.com/5341142/200957054-83fc8e58-f65d-4d7f-9737-141997a7a367.png)

Without being able to use named references, schema re-use becomes inefficient.  Imagine a situation where you have an `Author` schema that is shared by `Post`, `MediaBook`, and `Product` entities.  Defining the schema once in `#/components/schemas/` allows many different paths to reference the same schema and the Parser only has to output it once instead of over and over.

Finally, the SwaggerUI (and other UI swagger tools) display the list of all schemas at the bottom of the document to help API consumers know what the schema definitions are for quick reference:

![image](https://user-images.githubusercontent.com/5341142/200957471-d91d69e4-9cae-455f-b8ba-51acde56f260.png)

However, the UI components expect these definitions in the root of the document (i.e. `components.schemas`)

I'm just thinking out loud now, but perhaps one way to solve the problem, and give the users flexibility to write documentation in the way you mentioned above would be to have a new `$schemas` key which would be parsed similarly to `$allOf`, but in this case, the struct would be appended to /components/schemas?

By the way, this is probably how I would re-write the response definition.  The idea is that the response itself is unique because it extends the `Response` schema and includes the `Product` schema in the `response.data` key.

```
{
  "responses": {
    "200": {
      "description": "200-Success",
      "content": {
        "application/json": {
          "schema": {
            "$allOf": [
              {
                "$ref": "../../_schemas/response.json"
              },
              {
                "type": "object",
                "properties": {
                  "data": {
                    "description": "A single Product",
                    "$ref": "#/components/schemas/Product"
                  }
                }
              }
            ]
          }
        }
      }
    }
  }
}
```

The above has the following benefits:
 - We use the new $allOf to dynamically extend the response.json file (code re-use)
 - We extend the `data` key with the reference to the `components.schemas` definition `Product`
 - The `Product` schema is defined per the swagger spec and will be available in the UI as a separate definition.
 
 What do you think?

**Comment by jclausen** [comment]
The concerns addressed in this one should be resolved by the SDK change to maintain any `$ref` objects in the document which cannot be resolved.  This way, any references to the root document can be resolved when the normalized swagger doc is parsed.  This will allow you to use your root level `components.schemas` to be resolved, while still maintaining support for self referenced keys of the same name in the documents being sourced.
