### ISSUE TITLE
Add support for root file polymorphism

### ISSUE THREAD

**Issue by jclausen** [coldbox-modules/cbSwagger#35]
This was added in OpenAPI v3 and should be supported: https://swagger.io/docs/specification/data-models/inheritance-and-polymorphism/

**Comment by homestar9** [comment]
Thanks @jclausen! This would be a great feature!

**Comment by jclausen** [comment]
The inheritance `$ref` handling has been resolved in the latest snapshot.  @homestar9 if you could PR your work on `allOf` I will merge that in and we can move toward closing this one out.  Thanks!

**Comment by homestar9** [comment]
Nice work @jclausen! I am excited to test.  I'll get started on that PR.

**Comment by jclausen** [comment]
This is resolved in the latest snapshot of `swagger-sdk` and will be released in version 3.0.0
