### ISSUE TITLE
Forgebox Missing 2.7.0

### ISSUE THREAD

**Issue by homestar9** [coldbox-modules/cbSwagger#36]
For some reason, Forgebox.io lists version 2.6.0+147 as being the most current.  Executing `box install cbSwagger` installs that version.

However, on Github, the latest version as of today is 2.7.0.

![image](https://user-images.githubusercontent.com/5341142/200087930-3a8aec61-5e22-47d8-ac8c-88528fa9e170.png)

**Comment by jclausen** [comment]
@homestar9 I am going to run a manual build.  It looks like the last deploy failed due to a failing ACF2016 test.  https://app.travis-ci.com/github/coldbox-modules/cbSwagger/builds/257518760
