### ISSUE TITLE
Bug in RoutesParser.cfc

### ISSUE THREAD

**Issue by mograff** [coldbox-modules/cbSwagger#5]
I was getting an error in the RoutesParser.cfc line 103. It looks like it is trying to listToArray an existing array. To get to work I change the line from:
route[ "moduleInvocationPath" ] =listToArray( moduleConventionPath, "." );
to:
route[ "moduleInvocationPath" ] = moduleConventionPath;

**Comment by lmajano** [comment]
this should be fixed now
