### ISSUE TITLE
Cannot access /cbswagger

### ISSUE THREAD

**Issue by adelisle-cegid** [coldbox-modules/cbSwagger#6]
On a clean set-up of coldbox (rest template), I'm trying to access the route /cbswagger but I'm getting the following error:

Event: cbswagger:Main.index 
Routed URL: cbswagger/ 
Layout: N/A (Module: ) 
View: N/A 
Timestamp: 09/21/2018 10:42:51 AM
Type: InterceptorService.InterceptorNotFound 
Messages: Interceptor: SES not found in any state: onRequestCapture,preProcess,afterInstanceAutowire.

This seems related to the fact that it tries to access this through injection: coldbox:interceptor:SES.
However, it appears to be deprecated according to source code in coldbox.

**Comment by adelisle-cegid** [comment]
Using coldbox 5.1.4.

**Comment by lmajano** [comment]
I have resolved this now in the latest push and will release today.

**Comment by adelisle-cegid** [comment]
Just tested, there seems to be a typo in `models/RoutesParser.cfc`

It is
`if( listFirst( controller.getSetting( "version", true ), "." ) gt 5 ){`
and was probably meant to be
`if( listFirst( controller.getSetting( "version", true ), "." ) gte 5 ){`

After changing that, seems to work fine at a quick glance.

**Comment by lmajano** [comment]
Thanks, fixed!
