### ISSUE TITLE
Access to atheists

### ISSUE THREAD

**Issue by petmakris** [coldbox-modules/cbSwagger#8]
I see in the end of Readme

```
Because of His grace, this project exists. If you don't like this, then don't read it, its not for you.
```
Will this software conflict with the rest of my code? My code base does not exist because of His grace for sure, I wonder of the implications.

**Comment by lmajano** [comment]
Dear Petros.

The line in the readme is a personal thanks and dedication of what I believe in.  It is a representation of my faith, not anybody’s faith.  It’s like writing a dedication in a book, this is my dedication.  There are no implications at all :)

Have a blessed week

Luis
